# Generated by Django 2.1.4 on 2019-04-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_obj', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tea', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='teach',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
